onclite: vintf: FCM: Declare missing AIDL HALs entries
The following HALs in device manifest are not declared in FCM <= level 5:
  android.hardware.biometrics.fingerprint@2.3::IBiometricsFingerprint/default
  android.hardware.bluetooth.audio.IBluetoothAudioProviderFactory/default (@4)
  android.hardware.cas.IMediaCasService/default (@1)
  android.hardware.drm.IDrmFactory/clearkey (@1)
  android.hardware.power.IPower/default (@3)
  android.hardware.usb@1.3::IUsb/default
  android.hardware.wifi.IWifi/default (@2)
  android.hardware.wifi.hostapd.IHostapd/default (@2)
  android.hardware.wifi.supplicant.ISupplicant/default (@3)
COMPATIBLE

ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    com.fingerprints.extension@2.0::IFingerprintEngineering/default
    com.fingerprints.extension@2.0::IFingerprintNavigation/default
    com.fingerprints.extension@2.0::IFingerprintSensorTest/default
    vendor.goodix.hardware.fingerprint@1.0::IGoodixBiometricsFingerprint/default

Change-Id: Ide8c9b31759f6acad5fe45f5cffac01374f69fbe